// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

namespace WebApp.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    [Migration("20201214023302_20201214")]
    partial class _20201214
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApp.Models.FruitModel", b =>
                {
                    b.Property<int>("fruitidx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fruitidx")
                        .HasColumnType("int(11)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_bin");

                    b.HasKey("fruitidx")
                        .HasName("PRIMARY");

                    b.ToTable("fruit");
                });

            modelBuilder.Entity("WebApp.Models.GoodsModel", b =>
                {
                    b.Property<int>("goodsidx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("goodsidx")
                        .HasColumnType("int(11)");

                    b.Property<int>("price")
                        .HasColumnName("price")
                        .HasColumnType("int(11)");

                    b.Property<int>("storeidx")
                        .HasColumnName("storeidx")
                        .HasColumnType("int(11)");

                    b.HasKey("goodsidx")
                        .HasName("PRIMARY");

                    b.ToTable("goods");
                });

            modelBuilder.Entity("WebApp.Models.OrderModel", b =>
                {
                    b.Property<int>("orderidx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("orderidx")
                        .HasColumnType("int(11)");

                    b.Property<int>("goodsidx")
                        .HasColumnName("goodsidx")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("orderdate")
                        .HasColumnType("datetime");

                    b.HasKey("orderidx")
                        .HasName("PRIMARY");

                    b.ToTable("order");
                });

            modelBuilder.Entity("WebApp.Models.StoreModel", b =>
                {
                    b.Property<int>("storeidx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("storeidx")
                        .HasColumnType("int(11)");

                    b.Property<string>("delegatename")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_bin");

                    b.Property<string>("storename")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_bin");

                    b.HasKey("storeidx")
                        .HasName("PRIMARY");

                    b.ToTable("store");
                });
#pragma warning restore 612, 618
        }
    }
}
